version: "3.6"
services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgrespassword
    graphql-engine:
        # image: hasura/graphql-engine:latest
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./migrations:/hasura-migrations
            - ./metadata:/hasura-metadata
        depends_on:
            - "postgres"
        restart: always
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
            HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
            HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
volumes:
    db_data:
